### ISSUE TITLE
Erro Laravel 5

### ISSUE THREAD

**Issue by giovannefc** [cagartner/correios-consulta#1]
Olá. Ele não encontra a classe Soap.

Já testou no laravel 5?

**Comment by cagartner** [comment]
Bom dia, ainda não tive tempo para criar uma versão para a Laravel 5, essa semana vou atualizar ela. Abração!

**Comment by cagartner** [comment]
Olá, acabei de testar em uma aplicação L5 e está funcionando perfeitamente, acredito que você precisa ativar a extensão soap no seu php: http://rotinadigital.net/habilitando-a-extensao-soap-no-php/

**Comment by giovannefc** [comment]
Boa tarde, Carlos.
Desculpe, pouco tempo depois me dei conta disso e habilitei a extensão Soap no meu servidor e acabei esquecendo de notificar aqui. Mas pelo menos você já sabe que funciona com o L5, rsrs..

Abs.
