### ISSUE TITLE
Erro ao instalar no Laravel 5.4

### ISSUE THREAD

**Issue by neibarros** [cagartner/correios-consulta#14]
Erro:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cagartner/correios-consulta 0.1.6 requires cagartner/phpquery 0.9.8 -> satisfiable by cagartner/phpquery[0.9.8].
    - Installation request for cagartner/correios-consulta ^0.1.6 -> satisfiable by cagartner/correios-consulta[0.1.6].
    - Conclusion: remove sabberworm/php-css-parser 6.0.1
    - Conclusion: don't install sabberworm/php-css-parser 6.0.1
    - cagartner/phpquery 0.9.8 requires sabberworm/php-css-parser 5.1.* -> satisfiable by sabberworm/php-css-parser[5.1.0, 5.1.1, 5.1.2].
    - Can only install one of: sabberworm/php-css-parser[5.1.0, 6.0.1].
    - Can only install one of: sabberworm/php-css-parser[5.1.1, 6.0.1].
    - Can only install one of: sabberworm/php-css-parser[5.1.2, 6.0.1].
    - Installation request for sabberworm/php-css-parser (locked at 6.0.1) -> satisfiable by sabberworm/php-css-parser[6.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by cagartner** [comment]
Opa.

Por acaso você já instalou o sabberworm/php-css-parser em outra lib?

Acabei de baixar e testar a instalação com sucesso:

```
Package operations: 3 installs, 0 updates, 0 removals
  - Installing sabberworm/php-css-parser (5.1.2): Loading from cache
  - Installing cagartner/phpquery (0.9.8): Loading from cache
  - Installing cagartner/correios-consulta (0.1.6): Downloading (100%)         
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
```

**Comment by neibarros** [comment]
Opa,

Vou dar uma olhada aqui.

**Comment by neibarros** [comment]
Cara,

Muito obrigado pela resposta rápida.
Era isso mesmo, tinha uma lib que estava usando o sabberworm/php-css-parser em uma versão maior, já resolvi aqui, está funcionando perfeitamente.
Vlw mesmo!
