### ISSUE TITLE
-888 Erro ao calcular tarifa no SGPB. CEP de origem não pode postar para o CEP de destino informado(-1).

### ISSUE THREAD

**Issue by kneipp** [cagartner/correios-consulta#16]
[RESOLVIDO]
Não é uma issue, só uma dúvida que fica registrada caso alguém mais precise.
Implementei a solução usando a lib e fiz vários testes.
Estou tendo dificuldade pois os Correios quase sempre retornam erro para PAC Contrato (4669) ao mesmo tempo que retornam com sucesso PAC (4510) e Sedex Contrato (4162). 
O que pode ser esse erro indicado pelo webservice? 
Algo em relação ao contrato do cliente que não abrange PAC mais abranje Sedex? 

 `    "codigo" => 4669
    "valor" => 0.0
    "prazo" => 0
    "mao_propria" => 0.0
    "aviso_recebimento" => 0.0
    "valor_declarado" => 0.0
    "entrega_domiciliar" => false
    "entrega_sabado" => false
    "erro" => array:2 [▼
      "codigo" => -888.0
      "mensagem" => "Erro ao calcular tarifa no SGPB. CEP de origem não pode postar para o CEP de destino informado(-1)."
    ]
  ]`

`  0 => array:9 [▼
    "codigo" => 4510
    "valor" => 16.1
    "prazo" => 5
    "mao_propria" => 0.0
    "aviso_recebimento" => 0.0
    "valor_declarado" => 0.0
    "entrega_domiciliar" => true
    "entrega_sabado" => false
    "erro" => array:2 [▼
      "codigo" => 0.0
      "mensagem" => ""
    ]
  ]`

`  2 => array:9 [▼
    "codigo" => 4162
    "valor" => 9.94
    "prazo" => 1
    "mao_propria" => 0.0
    "aviso_recebimento" => 0.0
    "valor_declarado" => 0.0
    "entrega_domiciliar" => true
    "entrega_sabado" => true
    "erro" => array:2 [▶]
  ]`

**Comment by voope** [comment]
pra mim só retorna erro, nao consegui fazer funcionar.

**Comment by kneipp** [comment]
Olá, no meu caso o erro -888 indica que os Correios não estão atendendo a região com o PAC CONTRATO, segundo contato com um funcionário (informação não oficial) o serviço será descontinuado.
