### ISSUE TITLE
Endpoint de busca de CEP parou de responder

### ISSUE THREAD

**Issue by rafaelqm** [cagartner/correios-consulta#20]
Provavelmente removeram hoje 03/10/2017 o endereço do ar, http://m.correios.com.br/movel/buscaCepConfirma.do, não está retornando nada.

**Comment by cagartner** [comment]
@rafaelqm Recebi agora a pouco um PR para modificar isso, vou validar e assim que estiver ok atualizo a tag :)

**Comment by rafaelqm** [comment]
@cagartner Fiz uma PR apontando pro novo endpoint pra mim já funcionou aqui (troquei direto na pasta vendor apenas temporariamente).

**Comment by cagartner** [comment]
PR aceita, pode dar um compsoer update no projeto que já vai baixar com a correção.

Foi só verifique no composer se a versão está: 0.1.*

Muito obrigado pela contribuição!
