### ISSUE TITLE
composer update

### ISSUE THREAD

**Issue by sotnaspina** [cagartner/correios-consulta#22]
O "composer update" esta atualizando o pacote para a versão 0.1.8 e não a ultima versão 0.1.9

**Comment by brunobacha** [comment]
Mesma coisa aqui, estou utilizando Laravel 5.4. CEP parou de funcionar.

**Comment by cagartner** [comment]
Verifique seu composer require se a versão está 0.1.9

**Comment by marceloporto** [comment]
Problem 1
    - Installation request for cagartner/correios-consulta 0.1.9 -> satisfiable by cagartner/correios-consulta[0.1.9].
    - cagartner/correios-consulta 0.1.9 requires phpunit/phpunit ^6.4@dev -> satisfiable by phpunit/phpunit[6.4.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by brunobacha** [comment]
Colocando 0.1.9, apareceu o erro como @marceloporto reportou.

**Comment by cagartner** [comment]
Tentem atualizar para 0.1.10  removi o phpunit do composer

**Comment by brunobacha** [comment]
Deu certo! Bom trabalho!

**Comment by marceloporto** [comment]
Agora sim. Maravilha ;-)

**Comment by cagartner** [comment]
Show :)
