### ISSUE TITLE
Atualizar biblioteca.

### ISSUE THREAD

**Issue by ianitsky** [cagartner/correios-consulta#30]
Opa, 

Faça o update do pacote         "cagartner/phpquery": "0.9.8" para o 0.9.9

Valew

**Comment by hbtsmith** [comment]
ian, essa desatualização está causando algum erro?

**Comment by cagartner** [comment]
Opa, tudo certo?

Tenta atualizar a bilblioteca apra a seguinte versão: 

`"cagartner/correios-consulta": "0.2.*"`
