### ISSUE TITLE
Parou de funcionar?

### ISSUE THREAD

**Issue by hbtsmith** [cagartner/correios-consulta#31]
Aparentemente parou de funcionar o retorno do rastreamento. Será que é coisa do correios?

Uma outra coisa:
Aparentemente há um resto de debug no código:
`$c            = 0;

        foreach (phpQuery::pq('tr') as $tr)
        {
            $c++;`

Que seria essa var $c

**Comment by AlexMacha** [comment]
Aqui também

**Comment by cagartner** [comment]
Bom dia.

Ainda está com problema? Só vou poder verificar isso amanhã a noite.

Tenho que refatorar esse código, faz anos que fiz e falta muitas boas práticas nesse projeto rsrsrs

Abraços!

**Comment by cagartner** [comment]
Acabei de atualizar o módulo com algumas melhorias, pdoe atualizar ai e ver se está ok agora?
