### ISSUE TITLE
Última atualização quebrou a mensagem de erro do retorno

### ISSUE THREAD

**Issue by rodrigopeixotobr** [cagartner/correios-consulta#33]
Na última atualização, o novo arquivo CorreiosHelper, na linha 131 está transformando em número a mensagem do erro:

`'erro' => array('codigo' => (real) $rate->Erro, 'mensagem' => (real) $rate->MsgErro),`

Pelo que percebi deveria ser sem esse (real), ou seja:

`'erro' => array('codigo' => (real) $rate->Erro, 'mensagem' => $rate->MsgErro),`

Abraços.

**Comment by cagartner** [comment]
Olá @rodrigopeixotobr.

Obrigado pelo aviso.

To bem sem tempo de ver isso, se puder abrir um PR para isso iria ajudar muito.

Abraços!

**Comment by rodrigopeixotobr** [comment]
@cagartner  aberto o PR:
#40
