### ISSUE TITLE
Função de cálculo de frete com mais de 1 tipo

### ISSUE THREAD

**Issue by tulipia** [cagartner/correios-consulta#34]
Quando é inserido mais de um tipo por vírgula como indicado no código na variável dados na função Correios::frete, a função apenas retorna um array.

`$dados = [
	        'tipo'              => 'pac', 'sedex',
	        'formato'           => 'caixa',
	        'cep_destino'       => '74075150',
	        'cep_origem'        => $cep, 
	        //'empresa'         => '', 
	        //'senha'           => '', 
	        'peso'              => '1',
	        'comprimento'       => '16',
	        'altura'            => '11', 
	        'largura'           => '11',
	        'diametro'          => '0', 
	        // 'mao_propria'       => '1',
	        // 'valor_declarado'   => '1',
	        // 'aviso_recebimento' => '1',
	    ];
	    dd(Correios::frete($dados));`

**Comment by cagartner** [comment]
Olá @tulipia 

Você deve inserir no mesmo elemento com virgula e sem espaço:

```php
$dados = [
    'tipo'   => 'sedex,pac',
    // ...
];
echo Correios::frete($dados);
```
Abraços!

**Comment by tulipia** [comment]
Estava tentando dessa forma, mas com espaços. Obrigado
