### ISSUE TITLE
Espaços em branco no fim das linhas

### ISSUE THREAD

**Issue by roalvesrj** [cagartner/correios-consulta#35]
Estou utilizando o pacote para consulta de CEP em minha aplicação, porém, identifiquei que cada linha retornada está apresentando um carácter em branco ao final de cada linha do array, ex: "logradouro" : "Rua XYZ ","cidade" : "São Paulo ". Tem como contornar isso?

**Comment by cagartner** [comment]
Olá @roalvesrj 
você pode usar a função `trim()` para remover esse espaço:
https://www.php.net/manual/pt_BR/function.trim.php

Eu posso implementar isso futuramente mas no momento estou sem tempo, caso vc queria contribuir basta fazer um fork ajustar e enviar um pull request.

Abraços!

**Comment by roalvesrj** [comment]
@cagartner já enviei um pull request com o problema consertado. Na verdade você já utilizava o trim(), porém, ele não trata espaços em branco quando estão dentro do DOM, usei uma expressão regular para corrigir.

Abraços!

**Comment by cagartner** [comment]
Obrigado pela contribuição.

PR aprovado.
