### ISSUE TITLE
recursos absoletos com PHP 7.4

### ISSUE THREAD

**Issue by Helidalto** [cagartner/correios-consulta#39]
Precisando apenas destes ajustes para rodar legal no php7.4 pelo que vi.
{0} para [0];
(real) para (float);

**Comment by Ricassj** [comment]
Depois que dá os requires da instalação tem que fazer o banco de dados amigo pode dar uma ajuda pra instalar?

**Comment by brunobacha** [comment]
Up!

The (real) cast is deprecated, use (float) instead
Cagartner/CorreiosConsulta/CorreiosConsulta.php:131

**Comment by cagartner** [comment]
Obrigado @brunobacha pela contribuição: 

Pessoal que está usando 7.3 + para favor atualizem para a seguinte versão: 

`"cagartner/correios-consulta": "0.2.*"`
