### ISSUE TITLE
Depreciado

### ISSUE THREAD

**Issue by paulosfjunior** [cagartner/correios-consulta#42]
Nos arquivos abaixo tem que realizar as seguintes modificações:

PhpQuery.php linha 120
De:  if ($ns{0} !== '\\') {
Para: if ($ns[0] !== '\\') {

PhpQueryObject.php linha 1097
De:  if ($param{0} == 'n')
Para: if ($param[0] == 'n')

**Comment by roalvesrj** [comment]
@paulosfjunior criei a pull request com a correção informada no repositório correto, agora é aguardar o @cagartner verificar se está tudo certo. Tive o mesmo problema que você aqui. Obrigado por apontar.

**Comment by roalvesrj** [comment]
@cagartner essa questão já foi solucionada no PR mencionado acima.

**Comment by cagartner** [comment]
Por favor atualizar sua versão para : `"cagartner/correios-consulta": "0.3.*"`
