### ISSUE TITLE
Deprecated php 7.4

### ISSUE THREAD

**Issue by roalvesrj** [cagartner/correios-consulta#46]
@cagartner observei que com os últimos PRs enviados, as correções realizadas na issue #39 foram perdidas. Estou rodando a versão 0.2.3 e o erro `The (real) cast is deprecated, use (float)` permanece. Caso queira, posso enviar um PR com a correção.

**Comment by roalvesrj** [comment]
Aproveitando para informar que a dependência do phpquery ainda está para a versão obsoleta 0.9.11, ao invés da que corrige a compatibilidade com a versão 7.4 do PHP (0.9.12)

**Comment by cagartner** [comment]
Opa, desculpa um PR acabou voltando as alterações do outro, por favor atualizar sua versão para: 

    "cagartner/correios-consulta": "0.3.*"
